name: Continuous Integration

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Prevent from running on release commits
  skip_on_release:
    name: Skip on Release
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(master)') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 0

  stylua:
    name: Stylua
    needs:
      - skip_on_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua

  tests:
    name: Tests
    needs:
      - stylua
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        nvim-versions: ["stable", "nightly"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}
      - name: Neovim Version
        run: nvim --version
      - name: colors-wal.vim (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p "$HOME/AppData/Local/wal/"
          cp ./tests/colors-wal.vim "$HOME/AppData/Local/wal/"
      - name: colors-wal.vim (Ubuntu/MacOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p "$HOME/.cache/wal/"
          cp ./tests/colors-wal.vim "$HOME/.cache/wal/"
      - name: Lazy.nvim Tests
        run: |
          nvim --headless -V -u tests/lazy.lua +q
      - name: Plenary Tests
        run: nvim --headless --noplugin -V -u tests/plenary.lua -c "PlenaryBustedDirectory tests/ { minimal_init = './tests/plenary.lua', sequential = true }"

  docs:
    name: Gen Vimdoc
    needs:
      - stylua
      - tests
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gen Vimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: neopywal
          description: "(Neo)pywal for (Neo)vim"
          pandoc: "README.md"
          toc: true
          version: "nvim >= 0.8.0"
          treesitter: true
      - name: Commit Docs
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto generate vimdoc"
          branch: ${{ github.head_ref }}
