name: PR Linting

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          scopes: |
            .+
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            merge
            perf
            refactor
            revert
            style
            test
            wip
          ignoreLabels: |
            autorelease: pending

  stylua:
    name: Stylua
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua
