name: Gen Vimdoc

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Prevent from running on release commits
  skip_on_release:
    name: Skip on Release
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(master)') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 0

  docs:
    name: Gen Vimdoc
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Gen Vimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: neopywal
          description: "(Neo)pywal for (Neo)vim"
          pandoc: "README.md"
          toc: true
          version: "nvim >= 0.8.0"
          treesitter: true
      - name: Commit Docs
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto generate vimdoc"
          branch: ${{ github.head_ref }}
